spring:
  application:
    name: car-rental

  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental
    username: a11
    password: aset-admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ????? ??????????, ????? ????? 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  jwt:
    secret: "bM23WSufUiMjUfob57+S8/FUlPbLlxWBYs1wnAQv5vYy9Znfd2vDmfeQwHsH8XT2"
    access-token-ttl-minutes: 60

server:
  port: 8080
